# This is a basic workflow to help you get started with Actions

name:  Movie Corns CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Installs flutter
    - name : Get Flutter from github
      run:  git clone https://github.com/flutter/flutter.git -b stable
    #add to the path
    - name: Add flutter to the path
      run: export PATH="$PATH:`pwd`/flutter/bin"
    # Flutter check
    - name : Flutter Doctor Check
      run: flutter doctor 
    # Runs a set of commands using the runners shell
    - name: Flutter Get Packages
      run: flutter pub get
    - name: Flutter Run
      run: flutter run
